// Every level is solvable, and par comes from the solver (Plan/01-one-more-step.md §14): its shortest
// solution, recorded here, replays to a win in exactly that many steps (the rules are deterministic).
//
// UPDATE_SOLUTIONS=1 pnpm vitest run src/games/one-more-step/levels/solutions.test.ts
// solves every level again and rewrites solutions.ts (after a level or a rule changes).
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { compile } from "../engine/course";
import { replay, solve } from "../engine/solver";
import { getLevel, LEVEL_IDS } from "./index";
import { SOLUTIONS } from "./solutions";

const UPDATE = process.env.UPDATE_SOLUTIONS === "1";

if (UPDATE) {
  it("solves every level", { timeout: 600_000 }, () => {
    const lines = LEVEL_IDS.map((id) => {
      const sol = solve(compile(getLevel(id)));
      if (!sol) throw new Error(`${id}: no solution`);
      return `  "${id}": { steps: ${sol.steps}, moves: "${sol.moves}" },`;
    });
    writeFileSync(
      join(process.cwd(), "src/games/one-more-step/levels/solutions.ts"),
      `// Generated by levels/solutions.test.ts (UPDATE_SOLUTIONS=1): the solver's shortest solution for every
// level (one letter per action: U R D L, "." to wait). Par comes from these.

export const SOLUTIONS: Record<string, { steps: number; moves: string }> = {
${lines.join("\n")}
};
`,
    );
  });
} else {
  describe("the solver's solutions", () => {
    it.each(LEVEL_IDS)("%s: the recorded solution wins, in exactly its steps, and there's none shorter", (id) => {
      const rec = SOLUTIONS[id];
      expect(rec, "a solution").toBeDefined();
      const c = compile(getLevel(id));
      const end = replay(c, rec!.moves);
      expect(end.status).toBe("won");
      expect(end.tick).toBe(rec!.steps);
      expect(solve(c)!.steps).toBe(rec!.steps);
    });
  });
}
