// World 2, Catch the Door: herding it in open rooms, with holes, spikes and your own crumbling trail as walls; moving floors; a painted door. (Plan/01-one-more-step.md §5)
// Maps checked by the solver (levels/solutions.ts); see engine/types.ts for the legend.
import type { LevelDef } from "../engine/types";

export const WORLD_2: LevelDef[] = [
  {
    id: "2-1",
    world: 2,
    name: "Herding",
    map: [
      "#######",
      "#.....#",
      "#P..E.#",
      "#.....#",
      "###.###",
      "#######",
    ],
    narrator: [{ at: "start", text: "Doors run. Rooms have corners." }],
  },
  {
    id: "2-2",
    world: 2,
    name: "Moving Walkway",
    map: [
      "#########",
      "#..>>>..#",
      "##E...P##",
      "#########",
    ],
    narrator: [{ at: "start", text: "Please hold the handrail." }, { at: "run", text: "It's taking the walkway. Cheeky." }],
  },
  {
    id: "2-3",
    world: 2,
    name: "Draw Your Own Trap",
    map: [
      "#######",
      "#~~~~~#",
      "#~~~~~#",
      "#P~E~~#",
      "#~~~~~#",
      "#~~~~~#",
      "#######",
    ],
    narrator: [{ at: "start", text: "Every step you take is a hole it won't cross." }],
  },
  {
    id: "2-4",
    world: 2,
    name: "The Painted Door",
    map: [
      "###D###",
      "#.....#",
      "#P..h.#",
      "#.....#",
      "#######",
    ],
    door: "still",
    narrator: [{ at: "start", text: "There's the exit, on the wall. Nice paint job." }],
  },
  {
    id: "2-5",
    world: 2,
    name: "Holes",
    map: [
      "#########",
      "#..O....#",
      "#.E..O..#",
      "#.......#",
      "#..OO...#",
      "#..O..PO#",
      "#########",
    ],
    narrator: [{ at: "start", text: "The door won't go near a hole. Use that." }],
  },
  {
    id: "2-6",
    world: 2,
    name: "Spike Fence",
    map: [
      "#########",
      "#P...x..#",
      "#.O...E.#",
      "#.......#",
      "#.xx....#",
      "#.......#",
      "#.#######",
      "#########",
    ],
    narrator: [{ at: "start", text: "Spikes up: the door stays put. Spikes down…" }],
  },
  {
    id: "2-7",
    world: 2,
    name: "Rush Hour",
    map: [
      "##########",
      "#O.....P.#",
      "#.#.....##",
      "#...<<<<O#",
      "#...>>E..#",
      "#.#......#",
      "##########",
    ],
    narrator: [{ at: "start", text: "Rush hour. Keep left." }],
  },
  {
    id: "2-8",
    world: 2,
    name: "Breadcrumbs",
    map: [
      "#########",
      "#.E~.P..#",
      "#...X~..#",
      "#~X...~.#",
      "#......~#",
      "#~....~.#",
      "#########",
    ],
    narrator: [{ at: "start", text: "Leave a trail it can't cross." }],
  },
];
