// World 3, Echoes: your shadow walks your steps a few ticks late; plates and the gates they hold open. (Plan/01-one-more-step.md §5)
// Maps checked by the solver (levels/solutions.ts); see engine/types.ts for the legend.
import type { LevelDef } from "../engine/types";

export const WORLD_3: LevelDef[] = [
  {
    id: "3-1",
    world: 3,
    name: "Echo",
    map: [
      "##########",
      "#P.......#",
      "#.######.#",
      "#.....E..#",
      "##########",
    ],
    door: "still",
    echoDelay: 3,
    narrator: [{ at: "start", text: "You've got company. Don't turn round." }, { at: "death", text: "That was you. Well, earlier you." }],
  },
  {
    id: "3-2",
    world: 3,
    name: "Plate",
    map: [
      "##########",
      "#P._...|E#",
      "##########",
    ],
    door: "still",
    echoDelay: 3,
    narrator: [{ at: "start", text: "A plate holds the gate open. Something has to stand on it." }],
  },
  {
    id: "3-3",
    world: 3,
    name: "Hold the Door",
    map: [
      "###########",
      "#P..._.|.E#",
      "###########",
    ],
    door: "still",
    echoDelay: 4,
    narrator: [{ at: "start", text: "Patience. You'll catch up with yourself." }],
  },
  {
    id: "3-4",
    world: 3,
    name: "Close Behind",
    map: [
      "#########",
      "#P......#",
      "#.#####.#",
      "#._.|.E.#",
      "#########",
    ],
    echoDelay: 3,
    narrator: [{ at: "start", text: "Your shadow gets in the door's way too." }],
  },
  {
    id: "3-5",
    world: 3,
    name: "Echo Chamber",
    map: [
      "##########",
      "######.###",
      "#.....#..#",
      "#.#...~..#",
      "#E..P...~#",
      "##~......#",
      "#.O..#...#",
      "##########",
    ],
    echoDelay: 3,
    narrator: [{ at: "start", text: "Echo… echo…" }],
  },
  {
    id: "3-6",
    world: 3,
    name: "Two Plates",
    map: [
      "##############",
      "#P._...|._.|E#",
      "##############",
    ],
    door: "still",
    echoDelay: 4,
    narrator: [{ at: "start", text: "Two plates. One of you. Well, two of you." }],
  },
  {
    id: "3-7",
    world: 3,
    name: "Ahead of Myself",
    map: [
      "##########",
      "####.#####",
      "#..Px..~.#",
      "#...#..#.#",
      "#.....O..#",
      "#.....E..#",
      "#.#......#",
      "##########",
    ],
    echoDelay: 3,
    narrator: [{ at: "start", text: "Get ahead of yourself." }],
  },
  {
    id: "3-8",
    world: 3,
    name: "Myself, Later",
    map: [
      "##########",
      "######.###",
      "##......##",
      "P....~O..#",
      "#....#.E.#",
      "#..~...#.#",
      "#........#",
      "##########",
    ],
    echoDelay: 3,
    narrator: [{ at: "start", text: "Later, you'll thank yourself." }],
  },
];
