// World 4, Mirror, Mirror: a twin who moves the other way across, and stone sentinels. (Plan/01-one-more-step.md §5)
// Maps checked by the solver (levels/solutions.ts); see engine/types.ts for the legend.
import type { LevelDef } from "../engine/types";

export const WORLD_4: LevelDef[] = [
  {
    id: "4-1",
    world: 4,
    name: "Twin",
    map: [
      "###########",
      "#e..T.P..E#",
      "###########",
    ],
    door: "still",
    narrator: [{ at: "start", text: "Meet your twin. Your left is its right." }],
  },
  {
    id: "4-2",
    world: 4,
    name: "Out of Step",
    map: [
      "###########",
      "#e...#...E#",
      "#....TP...#",
      "#.........#",
      "###########",
    ],
    door: "still",
    narrator: [{ at: "start", text: "A wall stops one of you. Not both." }],
  },
  {
    id: "4-3",
    world: 4,
    name: "Sentinel",
    map: [
      "##########",
      "#P...O..E#",
      "#.##...#.#",
      "#....S...#",
      "##########",
    ],
    door: "still",
    narrator: [{ at: "start", text: "That statue moves when you do. Holes don't." }],
  },
  {
    id: "4-4",
    world: 4,
    name: "Stone Cold",
    map: [
      "#########",
      "#S.~~~.P#",
      "#.......#",
      "#.....E.#",
      "#########",
    ],
    narrator: [{ at: "start", text: "Stone sinks." }],
  },
  {
    id: "4-5",
    world: 4,
    name: "Two Halves",
    map: [
      "###########",
      "#...e....##",
      "#P#.....OT#",
      "#.......#.#",
      "#..E.#....#",
      "###########",
    ],
    door: "still",
    narrator: [{ at: "start", text: "Two halves, one brain." }],
  },
  {
    id: "4-6",
    world: 4,
    name: "Statues",
    map: [
      "##########",
      "#~.E.~#~.#",
      "#..S.....#",
      "#.....#..#",
      "#S.......#",
      "#O....P.##",
      "##########",
    ],
    door: "still",
    narrator: [{ at: "start", text: "They're slow. They're heavy. They never stop." }],
  },
  {
    id: "4-7",
    world: 4,
    name: "Mirror Room",
    map: [
      "###########",
      "#......x.E#",
      "#.....##.O#",
      "#...x.....#",
      "#.T..Oe.P.#",
      "###########",
    ],
    door: "still",
    narrator: [{ at: "start", text: "Mirror, mirror." }],
  },
  {
    id: "4-8",
    world: 4,
    name: "Stone and Shadow",
    map: [
      "###########",
      "#.........#",
      "##........#",
      "##P......S#",
      "##.....#..#",
      "##.OE.....#",
      "##.########",
      "###########",
    ],
    narrator: [{ at: "start", text: "Stone, shadow, and a door that runs." }],
  },
];
