// The clean-up star's targets (Plan/10-last-pixel.md §7 "Finish the clean-up under the target time"): the
// bot's clean-up of each level, plus 30%.
//
// UPDATE_TARGETS=1 pnpm vitest run src/games/last-pixel/levels/runs.test.ts
// plays every level again and rewrites targets.ts (after a level, a tool or the bot changes).
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { playClean } from "../core/bot";
import { HZ } from "../core/constants";
import { World } from "../core/world";
import { LEVEL_IDS, LEVELS } from "./index";
import { TARGETS } from "./targets";

const UPDATE = process.env.UPDATE_TARGETS === "1";

/** The bot's time plus 30%, up to the next half second. */
export const targetFor = (ticks: number) => Math.ceil((ticks * 1.3) / (HZ / 2)) * (HZ / 2);

if (UPDATE) {
  it("plays every level's clean-up again", { timeout: 600_000 }, () => {
    const lines = LEVELS.map((level) => {
      const w = new World(level);
      playClean(w);
      if (w.phase !== "wake") throw new Error(`${level.id}: the clean-up didn't finish`);
      return `  "${level.id}": ${targetFor(w.cleanTicks)},`;
    });
    writeFileSync(
      join(process.cwd(), "src/games/last-pixel/levels/targets.ts"),
      `// Generated by levels/runs.test.ts (UPDATE_TARGETS=1): the clean-up star's target per level (ticks), the
// bot's clean-up plus 30%, rounded up to half a second.

export const TARGETS: Record<string, number> = {
${lines.join("\n")}
};
`,
    );
  });
} else {
  describe("the clean-up targets", () => {
    it("are set for every level, from the bot's own run", () => {
      for (const id of LEVEL_IDS) expect(TARGETS[id], id).toBeGreaterThan(0);
    });
  });
}
