// World 3, Desktop Cleanup (Plan/10-last-pixel.md §5): a computer's screen, inside your screen. Erase the
// doodles, wipe the smudges. Pix hides under the HUD, plays dead on your actual monitor, and pretends to be
// a second mouse cursor.
import { BIG_KIT, FULL_KIT, level } from "./kit";
import { screen } from "./scenes";

export const WORLD_3 = [
  level({
    id: "3-01",
    world: 3,
    name: "Doodle",
    hint: "Someone's been drawing on the screen. Rub it out.",
    tools: ["eraser"],
    scene: () => screen({ seed: "3-01", wallpaper: "hills", mess: "doodles", amount: 0.4 }),
    pix: { speed: 8, flee: true },
    hunt: FULL_KIT,
  }),
  level({
    id: "3-02",
    world: 3,
    name: "Smudges",
    hint: "Fingerprints all over it. Wipe them off. (The panels over the game? You can drag them about.)",
    tools: ["sponge"],
    scene: () => screen({ seed: "3-02", wallpaper: "sea", mess: "smudges", amount: 0.4 }),
    pix: { speed: 8, tricks: ["hud"] },
    hunt: FULL_KIT,
  }),
  level({
    id: "3-03",
    world: 3,
    name: "Stuck Pixel",
    hint: "Is that a dead pixel on your monitor? A real one would still be there if you paused…",
    tools: ["eraser"],
    scene: () => screen({ seed: "3-03", wallpaper: "meadow", mess: "doodles", amount: 0.5 }),
    pix: { speed: 8, tricks: ["dead"] },
    hunt: FULL_KIT,
  }),
  level({
    id: "3-04",
    world: 3,
    name: "Two Cursors",
    hint: "Two mouse pointers? One of them isn't following your hand. Touch it with yours.",
    tools: ["sponge"],
    scene: () => screen({ seed: "3-04", wallpaper: "city", mess: "smudges", amount: 0.5 }),
    pix: { speed: 7, tricks: ["mimic"], mimic: "mirrorX" },
    hunt: FULL_KIT,
  }),
  level({
    id: "3-05",
    world: 3,
    name: "Wallpaper",
    hint: "Doodles on the hills. It runs, and it knows where the panels are.",
    tools: ["eraser"],
    scene: () => screen({ seed: "3-05", wallpaper: "hills", mess: "doodles", amount: 0.7 }),
    pix: { speed: 9, flee: true, tricks: ["hud"] },
    hunt: FULL_KIT,
  }),
  level({
    id: "3-06",
    world: 3,
    name: "Screensaver",
    hint: "Smudges on a starry night. Hard to see things in the dark.",
    tools: ["sponge"],
    scene: () => screen({ seed: "3-06", wallpaper: "night", mess: "smudges", amount: 0.6 }),
    pix: { speed: 8, camo: true, tricks: ["dead"] },
    hunt: FULL_KIT,
  }),
  level({
    id: "3-07",
    world: 3,
    name: "Desktop Icons",
    hint: "This time the other cursor gets up and down the wrong way round.",
    tools: ["eraser"],
    scene: () => screen({ seed: "3-07", wallpaper: "sea", mess: "doodles", amount: 0.6 }),
    pix: { speed: 9, flee: true, tricks: ["mimic"], mimic: "mirrorY" },
    hunt: FULL_KIT,
  }),
  level({
    id: "3-08",
    world: 3,
    name: "Fingerprints",
    hint: "So many fingerprints. So many Pixes. Then it hides.",
    tools: ["sponge"],
    scene: () => screen({ seed: "3-08", wallpaper: "meadow", mess: "smudges", amount: 0.8 }),
    pix: { speed: 8, flee: true, decoys: 4, tricks: ["hud"] },
    hunt: BIG_KIT,
  }),
  level({
    id: "3-09",
    world: 3,
    name: "Blue Screen",
    hint: "Dead pixel, then a second cursor. Your screen's fine. Probably.",
    tools: ["eraser"],
    scene: () => screen({ seed: "3-09", wallpaper: "night", mess: "doodles", amount: 0.8 }),
    pix: { speed: 9, flee: true, tricks: ["dead", "mimic"], mimic: "mirrorX" },
    hunt: BIG_KIT,
  }),
  level({
    id: "3-10",
    world: 3,
    name: "Clean Install",
    hint: "Doodles to erase, smudges to wipe (1 and 2 swap tools). Then every trick it knows on a screen.",
    tools: ["eraser", "sponge"],
    scene: () => screen({ seed: "3-10", wallpaper: "city", mess: "both", amount: 0.6 }),
    pix: { speed: 9, flee: true, tricks: ["hud", "dead", "mimic"], mimic: "mirrorY" },
    hunt: BIG_KIT,
  }),
];
