// World 2, Garden Day (Plan/10-last-pixel.md §5): the mower, the snow shovel and the pressure washer. Pix
// splits into decoys (at night, among the fireflies) and burrows under the surface.
import { COLD, FULL_KIT, level } from "./kit";
import { driveway, lawn, patio } from "./scenes";

export const WORLD_2 = [
  level({
    id: "2-01",
    world: 2,
    name: "Front Lawn",
    hint: "Hold on and the mower drives to your pointer. It's heavy: it takes the corners wide. And new: freeze (F, or ❄) stops Pix for a second.",
    tools: ["mower"],
    scene: () => lawn({ seed: "2-01", beds: [{ x: 8, y: 52, w: 26, h: 12 }], trees: [{ x: 100, y: 22, r: 9 }], gnome: { x: 116, y: 60 } }),
    pix: { speed: 8, flee: true },
    hunt: COLD,
    mower: { x: 6, y: 66 },
  }),
  level({
    id: "2-02",
    world: 2,
    name: "First Snow",
    hint: "Push the snow off the drive (onto the lawn). Let go on the drive and you leave it in a heap.",
    tools: ["shovel"],
    scene: () => driveway({ seed: "2-02", dir: "down", width: 40, snowman: true }),
    pix: { speed: 8, flee: true },
    hunt: COLD,
  }),
  level({
    id: "2-03",
    world: 2,
    name: "Patio Day",
    hint: "Blast the grime off the tiles. And new: bait (B, or ✦): a shiny pixel Pix can't resist.",
    tools: ["washer"],
    scene: () => patio({ seed: "2-03", tile: "terracotta", parasol: { x: 70, y: 34, r: 13, colours: ["#FF9E7D", "#FFFFFF"] }, pots: [[14, 12], [114, 60]] }),
    pix: { speed: 9, flee: true },
    hunt: FULL_KIT,
  }),
  level({
    id: "2-04",
    world: 2,
    name: "Fireflies",
    hint: "Mowing at dusk. Fireflies everywhere, and five pixels that glow. Only one of them keeps the beat.",
    tools: ["mower"],
    scene: () => lawn({ seed: "2-04", night: true, trees: [{ x: 28, y: 26, r: 10 }], beds: [{ x: 84, y: 42, w: 30, h: 12 }] }),
    pix: { speed: 6, decoys: 4 },
    hunt: FULL_KIT,
    mower: { x: 6, y: 66 },
  }),
  level({
    id: "2-05",
    world: 2,
    name: "Moss",
    hint: "Gone to ground. The detector knows where: scrub there with the washer and dig it out.",
    tools: ["washer"],
    scene: () => patio({ seed: "2-05", tile: "slate", table: { x: 40, y: 30 }, pots: [[110, 14], [100, 58]] }),
    pix: { speed: 7, tricks: ["burrow"] },
    hunt: FULL_KIT,
  }),
  level({
    id: "2-06",
    world: 2,
    name: "Stripes",
    hint: "A proper striped lawn. Five Pixes again, and they run.",
    tools: ["mower"],
    scene: () => lawn({ seed: "2-06", pond: { x: 92, y: 40, rx: 12, ry: 7 }, path: [[20, 24], [30, 28], [40, 24], [50, 28]], beds: [{ x: 6, y: 56, w: 40, h: 10 }] }),
    pix: { speed: 7, flee: true, decoys: 4 },
    hunt: FULL_KIT,
    mower: { x: 6, y: 46 },
  }),
  level({
    id: "2-07",
    world: 2,
    name: "Snowed In",
    hint: "A long drive, a lot of snow. And it's dug itself in somewhere.",
    tools: ["shovel"],
    scene: () => driveway({ seed: "2-07", dir: "across", width: 34, snowman: true }),
    pix: { speed: 8, flee: true, tricks: ["burrow"] },
    hunt: FULL_KIT,
  }),
  level({
    id: "2-08",
    world: 2,
    name: "Garden Path",
    hint: "Chequered tiles, and copies of Pix that don't blink on the beat.",
    tools: ["washer"],
    scene: () => patio({ seed: "2-08", tile: "checker", pots: [[16, 14], [112, 14], [16, 58], [112, 58]], parasol: { x: 64, y: 36, r: 11, colours: ["#7CC9C1", "#FFFFFF"] } }),
    pix: { speed: 8, flee: true, decoys: 4 },
    hunt: FULL_KIT,
  }),
  level({
    id: "2-09",
    world: 2,
    name: "Night Mow",
    hint: "Fireflies, decoys, and then it goes to ground.",
    tools: ["mower"],
    scene: () => lawn({ seed: "2-09", night: true, pond: { x: 40, y: 40, rx: 11, ry: 7 }, trees: [{ x: 100, y: 20, r: 9 }], gnome: { x: 112, y: 58 } }),
    pix: { speed: 7, decoys: 4, tricks: ["burrow"] },
    hunt: FULL_KIT,
    mower: { x: 6, y: 66 },
  }),
  level({
    id: "2-10",
    world: 2,
    name: "Garden Party",
    hint: "Mow the lawn and wash the patio before the guests come (1 and 2 swap tools).",
    tools: ["mower", "washer"],
    scene: () => lawn({ seed: "2-10", patio: { x: 70, y: 30, w: 50, h: 36 }, trees: [{ x: 22, y: 24, r: 9 }], beds: [{ x: 6, y: 50, w: 30, h: 14 }] }),
    pix: { speed: 9, flee: true, decoys: 3, tricks: ["burrow"] },
    hunt: FULL_KIT,
    mower: { x: 40, y: 66 },
  }),
];
