// World 1, Home Makeover (Plan/10-last-pixel.md §5): the roller, the brush and the sponge. Pix flees,
// then learns to blend in.
import { LENS, level, NET, TAP } from "./kit";
import { room, windowWipe } from "./scenes";

export const WORLD_1 = [
  level({
    id: "1-01",
    world: 1,
    name: "Fresh Coat",
    hint: "Paint the wall with the roller: drag over it. Every last bit of it.",
    tools: ["roller"],
    scene: () => room({ seed: "1-01", paint: "lavender", old: "plaster", plant: { x: 112 }, frames: [{ x: 56, y: 16, w: 16, h: 12 }] }),
    pix: { speed: 6, flee: true },
    hunt: TAP,
  }),
  level({
    id: "1-02",
    world: 1,
    name: "Around the Window",
    hint: "A wall with a window and a door in it. And a net: Shift-drag (or the net button) to trap whatever's left.",
    tools: ["roller"],
    scene: () => room({ seed: "1-02", paint: "mint", old: "wallpaper", window: { x: 76, y: 10, w: 34, h: 30, view: "hills" }, door: { x: 12 }, lamp: { x: 50 } }),
    pix: { speed: 8, flee: true },
    hunt: NET,
  }),
  level({
    id: "1-03",
    world: 1,
    name: "Trim",
    hint: "The wall's done. The skirting board and the frames want a fresh coat: the brush, for the fiddly bits.",
    tools: ["brush"],
    scene: () => room({ seed: "1-03", paint: "sky", trim: true, window: { x: 70, y: 12, w: 36, h: 30, view: "sea" }, door: { x: 14 }, plant: { x: 52 } }),
    pix: { speed: 8, flee: true },
    hunt: NET,
  }),
  level({
    id: "1-04",
    world: 1,
    name: "Spring Clean",
    hint: "Wipe the window with the sponge. It takes a few goes: little circles clean fastest.",
    tools: ["sponge"],
    scene: () => windowWipe({ seed: "1-04", view: "hills", panes: [2, 2], wall: "butter" }),
    pix: { speed: 8, flee: true },
    hunt: NET,
  }),
  level({
    id: "1-05",
    world: 1,
    name: "Magnolia",
    hint: "Some pixels are shy. If you can't see it, the magnifier (M, or 🔍) can.",
    tools: ["roller"],
    scene: () => room({ seed: "1-05", paint: "magnolia", old: "primer", sofa: { x: 34, w: 44, colour: "#7CC9C1" }, frames: [{ x: 90, y: 14, w: 14, h: 12 }] }),
    pix: { speed: 4, camo: true },
    hunt: LENS,
  }),
  level({
    id: "1-06",
    world: 1,
    name: "Nursery",
    hint: "Peach, with polka dots. Something in it is very nearly peach.",
    tools: ["roller"],
    scene: () => room({ seed: "1-06", paint: "peach", mural: "dots", old: "wallpaper", window: { x: 84, y: 12, w: 28, h: 26, view: "meadow" }, plant: { x: 20 }, shelf: { x: 30, y: 26, w: 30 } }),
    pix: { speed: 7, flee: true, camo: true },
    hunt: LENS,
  }),
  level({
    id: "1-07",
    world: 1,
    name: "Bay Window",
    hint: "Six panes of sea and sky. Wipe them all.",
    tools: ["sponge"],
    scene: () => windowWipe({ seed: "1-07", view: "sea", panes: [3, 2], wall: "teal", grime: 0.68 }),
    pix: { speed: 7, flee: true, camo: true },
    hunt: LENS,
  }),
  level({
    id: "1-08",
    world: 1,
    name: "Feature Wall",
    hint: "Stripes! It's quick on its feet today. Corner it.",
    tools: ["roller"],
    scene: () => room({ seed: "1-08", paint: "rose", mural: "stripes", old: "plaster", door: { x: 100 }, sofa: { x: 20, w: 50 }, lamp: { x: 80 } }),
    pix: { speed: 10, flee: true },
    hunt: LENS,
  }),
  level({
    id: "1-09",
    world: 1,
    name: "Picture Rail",
    hint: "Trim round the door and the window. Small brush, steady hand.",
    tools: ["brush"],
    scene: () => room({ seed: "1-09", paint: "butter", trim: true, window: { x: 18, y: 10, w: 40, h: 32, view: "city" }, door: { x: 96 }, frames: [{ x: 66, y: 16, w: 14, h: 12 }] }),
    pix: { speed: 8, flee: true, camo: true },
    hunt: LENS,
  }),
  level({
    id: "1-10",
    world: 1,
    name: "Open House",
    hint: "Paint the walls and wipe the window: the roller for one, the sponge for the other (1 and 2 swap them).",
    tools: ["roller", "sponge"],
    scene: () => room({ seed: "1-10", paint: "sage", old: "plaster", window: { x: 74, y: 10, w: 40, h: 32, view: "hills", dirty: true }, door: { x: 10 }, plant: { x: 62 } }),
    pix: { speed: 9, flee: true, camo: true },
    hunt: LENS,
  }),
];
