// World 4, Outside the Box (Plan/10-last-pixel.md §5): every tool. Pix leaves the canvas for the page
// around it, un-paints as it runs, and (in the bonus level) hides in the browser tab's icon.
import { BIG_KIT, level } from "./kit";
import { card, driveway, patio, room, windowWipe } from "./scenes";

export const WORLD_4 = [
  level({
    id: "4-01",
    world: 4,
    name: "Lucky Pixel",
    hint: "Scratch the card (the coin: scratch, scratch). Then look outside the box: the arrow at the edge points to it.",
    tools: ["scratch"],
    scene: () => card({ seed: "4-01", prizes: ["cherries", "cherries", "cherries"] }),
    pix: { speed: 9, flee: true, tricks: ["dom"], spots: ["percent"] },
    hunt: BIG_KIT,
  }),
  level({
    id: "4-02",
    world: 4,
    name: "Wet Paint",
    hint: "Fresh paint. Pix runs straight through it, and leaves a trail you'll have to paint again.",
    tools: ["roller"],
    scene: () => room({ seed: "4-02", paint: "coral", mural: "waves", old: "plaster", window: { x: 18, y: 12, w: 30, h: 28, view: "sea" }, plant: { x: 112 } }),
    pix: { speed: 10, flee: true, trail: 160 },
    hunt: BIG_KIT,
  }),
  level({
    id: "4-03",
    world: 4,
    name: "Logo",
    hint: "Snow on the drive. And something's up with the game's own name…",
    tools: ["shovel"],
    scene: () => driveway({ seed: "4-03", dir: "down", width: 48 }),
    pix: { speed: 9, flee: true, tricks: ["dom"], spots: ["logo"] },
    hunt: BIG_KIT,
  }),
  level({
    id: "4-04",
    world: 4,
    name: "Undo",
    hint: "Clean tiles, a pixel that blends in, and a trail of grime behind it.",
    tools: ["washer"],
    scene: () => patio({ seed: "4-04", tile: "stone", parasol: { x: 30, y: 30, r: 12, colours: ["#B7ABFF", "#FFFFFF"] }, pots: [[110, 56]] }),
    pix: { speed: 9, flee: true, camo: true, trail: 140 },
    hunt: BIG_KIT,
  }),
  level({
    id: "4-05",
    world: 4,
    name: "Toolbar",
    hint: "Six panels to scratch. Five Pixes. One of them is going to go and sit on a button.",
    tools: ["scratch"],
    scene: () => card({ seed: "4-05", prizes: ["star", "seven", "clover", "heart", "diamond", "pix"], rows: 2, theme: ["#7CC9C1", "#B7ABFF"] }),
    pix: { speed: 9, decoys: 4, tricks: ["dom"], spots: ["pause"] },
    hunt: BIG_KIT,
  }),
  level({
    id: "4-06",
    world: 4,
    name: "Backwards",
    hint: "A window at night. Wipe it clean, and keep it clean.",
    tools: ["sponge"],
    scene: () => windowWipe({ seed: "4-06", view: "night", panes: [2, 3], wall: "lavender" }),
    pix: { speed: 9, flee: true, trail: 140, tricks: ["hud"] },
    hunt: BIG_KIT,
  }),
  level({
    id: "4-07",
    world: 4,
    name: "Jackpot",
    hint: "Three sevens. Then a dead pixel, and then it's off out of the canvas.",
    tools: ["scratch"],
    scene: () => card({ seed: "4-07", prizes: ["seven", "seven", "seven"], theme: ["#FF9E7D", "#FFE49A"] }),
    pix: { speed: 10, flee: true, tricks: ["dead", "dom"], spots: ["logo", "percent"] },
    hunt: BIG_KIT,
  }),
  level({
    id: "4-08",
    world: 4,
    name: "Snow Day",
    hint: "It digs into the snow, and every step it takes un-clears the drive.",
    tools: ["shovel"],
    scene: () => driveway({ seed: "4-08", dir: "across", width: 40, snowman: true }),
    pix: { speed: 9, flee: true, trail: 120, tricks: ["burrow"] },
    hunt: BIG_KIT,
  }),
  level({
    id: "4-09",
    world: 4,
    name: "Everything",
    hint: "Walls and trim, then everything Pix has learned outside the canvas.",
    tools: ["roller", "sponge"],
    scene: () => room({ seed: "4-09", paint: "teal", mural: "sunset", old: "wallpaper", window: { x: 84, y: 10, w: 34, h: 30, view: "city", dirty: true }, door: { x: 8 }, sofa: { x: 32, w: 46, colour: "#FF9E7D" } }),
    pix: { speed: 10, flee: true, trail: 120, tricks: ["hud", "dom"], spots: ["percent", "logo", "pause"] },
    hunt: BIG_KIT,
  }),
  level({
    id: "4-10",
    world: 4,
    name: "Tab Escape",
    hint: "Bonus window. Wipe it, and keep an eye on your browser tab.",
    tools: ["sponge"],
    scene: () => windowWipe({ seed: "4-10", view: "snow", panes: [2, 2], wall: "sky" }),
    pix: { speed: 9, flee: true, tricks: ["tab"] },
    hunt: BIG_KIT,
    bonus: true,
  }),
];
