// The solver's runs: every window can be escaped (Plan/12-cursor-escape.md §14: "each finishable in 60 s or
// less once learned"), and its run, played back through the real simulation, escapes it again.
//
// UPDATE_DEV_RUNS=1 pnpm vitest run src/games/cursor-escape/levels/runs.test.ts
// re-solves every window (or just ONLY=C-01,E-04) and rewrites runs.ts and medals.ts, after a window or
// a rule changes.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { seconds } from "../core/constants";
import { compile } from "../core/sim";
import { replay, solve } from "../core/solver";
import { getLevel, LEVEL_IDS, LEVELS } from "./index";
import { ROUTES } from "./routes";
import { RUNS } from "./runs";

const UPDATE = process.env.UPDATE_DEV_RUNS === "1";

/** Up to the next tenth of a second (12 ticks). */
const tenth = (ticks: number) => Math.ceil(ticks / 12) * 12;

if (UPDATE) {
  it("re-solves every window", { timeout: 3_600_000 }, () => {
    const only = process.env.ONLY?.split(",");
    const runs = { ...RUNS };
    for (const id of LEVEL_IDS) {
      if (only && !only.includes(id)) continue;
      const course = compile(getLevel(id));
      const found = solve(course, { route: ROUTES[id] });
      if (!found) throw new Error(`${id}: no way out`);
      if (replay(course, found.moves).status !== "won") throw new Error(`${id}: the run doesn't replay`);
      runs[id] = { time: found.time, moves: found.moves };
    }
    const ids = LEVEL_IDS.filter((id) => runs[id]);
    writeFileSync(
      join(process.cwd(), "src/games/cursor-escape/levels/runs.ts"),
      `// Generated by levels/runs.test.ts (UPDATE_DEV_RUNS=1): the solver's way through each window (core/solver.ts:
// one character a move). The tests play every one back through the real simulation; the medal times
// (medals.ts) come from them.

export const RUNS: Record<string, { moves: string; time: number }> = {
${ids.map((id) => `  "${id}": { time: ${runs[id]!.time}, moves: "${runs[id]!.moves}" },`).join("\n")}
};
`,
    );
    writeFileSync(
      join(process.cwd(), "src/games/cursor-escape/levels/medals.ts"),
      `// Generated by levels/runs.test.ts (UPDATE_DEV_RUNS=1): medal times (ticks) from the solver's run through
// each window (runs.ts). Gold is its time plus 35%, silver gold × 1.6, bronze gold × 2.4.

export const MEDALS: Record<string, { gold: number; silver: number; bronze: number }> = {
${ids
  .map((id) => {
    const gold = tenth(runs[id]!.time * 1.35);
    return `  "${id}": { gold: ${gold}, silver: ${tenth(gold * 1.6)}, bronze: ${tenth(gold * 2.4)} },`;
  })
  .join("\n")}
};
`,
    );
  });
} else {
  describe("the solver's runs", () => {
    it.each(LEVEL_IDS)("%s: the run escapes, in under a minute", (id) => {
      const run = RUNS[id];
      expect(run, "a run").toBeDefined();
      const w = replay(compile(getLevel(id)), run!.moves);
      expect(w.status).toBe("won");
      expect(w.tick).toBe(run!.time);
      expect(run!.time).toBeLessThan(seconds(60));
    });

    it("set the medal times: gold, then silver, then bronze", () => {
      for (const level of LEVELS) {
        const { gold, silver, bronze } = level.medals;
        expect(gold, level.id).toBe(tenth(RUNS[level.id]!.time * 1.35));
        expect(silver, level.id).toBeGreaterThan(gold);
        expect(bronze, level.id).toBeGreaterThan(silver);
      }
    });
  });
}
