// Isaac's Tree (Plan/15-gravity-is-lying.md §5): four rooms up to Isaac, at the top. The drips, the dust
// and the lamps start lying too; only Newt's scarf is honest. To reach Isaac, make gravity point up
// and fall to the top.
import type { RoomSource } from "../core/room";

export const WORLD_6: RoomSource[] = [
  {
    id: "6-01",
    name: "Roots",
    gravity: "up",
    zones: [
      { area: [1, 1, 8, 15], dir: "down" },
    ],
    anchorsLie: "down",
    arrowLie: "down",
    net: true,
    signs: ["Even the water lies up here. Trust your scarf."],
    isaac: [
      { text: "Welcome to my tree! Down is down here. Ask the water.", lie: true, truth: "Out there, gravity pulls up. The water's lying for me. Your scarf won't." },
      { text: "Hmph. That scarf of yours is very rude.", lie: false, at: [10, 1, 18, 15] },
    ],
    route: [[4, 13], [4, 12], [7, 14], [13, 8], [17, 1], [21, 4], [24, 1]],
    map: [
      "##############################",
      "#........^^^^^............O..#",
      "#............................#",
      "#..................d.........#",
      "#.....I..............a.......#",
      "#...........d................#",
      "#............................#",
      "#.......................l....#",
      "#............a...............#",
      "#...............l............#",
      "#............................#",
      "#............................#",
      "#...a........................#",
      "#............................#",
      "#............................#",
      "#.S..s...^^^.................#",
      "##############################",
    ],
  },
  {
    id: "6-02",
    name: "Branches",
    gravity: "down",
    zones: [
      { area: [6, 1, 5, 15], dir: "up", painted: "down" },
      { area: [15, 9, 5, 7], dir: "down", painted: "up" },
      { area: [24, 1, 5, 7], dir: "up", painted: "down" },
    ],
    anchorsLie: "down",
    isaac: [
      { text: "The arrows on my branches are painted by the finest artists. They never lie.", lie: true, truth: "Every arrow here is painted wrong, and the water agrees with them. Your scarf doesn't." },
    ],
    route: [[5, 15], [8, 6], [8, 1], [10, 1], [12, 7], [14, 7], [17, 4], [20, 7], [22, 7], [23, 7], [25, 4], [26, 2]],
    map: [
      "##############################",
      "#..............^^^........O..#",
      "#............l...............#",
      "#............................#",
      "#.I.....a........a........d..#",
      "#............................#",
      "#............................#",
      "#.....................a......#",
      "#..........####.....####.....#",
      "#........d...................#",
      "#............................#",
      "#................d...........#",
      "#............................#",
      "#............................#",
      "#............................#",
      "#.S...^^^^^....^^^^^.........#",
      "##############################",
    ],
  },
  {
    id: "6-03",
    name: "Canopy",
    gravity: "down",
    anchorsLie: "down",
    arrowLie: "down",
    rotate: { every: 180, turn: "half" },
    isaac: [
      { text: "Nothing ever moves in my canopy. Calm, still, peaceful.", lie: true, truth: "It flips every three seconds. Listen for the hum: that never lies." },
    ],
    route: [[5, 15], [6, 1], [9, 1], [12, 1], [15, 15], [17, 15], [23, 1], [24, 15], [26, 15], [27, 2]],
    map: [
      "##############################",
      "#^^^.....a...^^^^..........O.#",
      "#............................#",
      "#............................#",
      "#........................l...#",
      "#............................#",
      "#....d.....##................#",
      "#..........##................#",
      "#..........##.......d........#",
      "#..........##................#",
      "#..........##................#",
      "#............................#",
      "#............................#",
      "#..........................I.#",
      "#............................#",
      "#.S....^^^^....a...^^^^.a....#",
      "##############################",
    ],
  },
  {
    id: "6-04",
    name: "The Top",
    gravity: "down",
    levers: ["down", "up"],
    anchorsLie: "down",
    arrowLie: "down",
    isaac: [
      { text: "You'll never get up here. Gravity's on my side. It always has been.", lie: true, truth: "Pull the lever. Gravity will bring you up to me. It always could." },
      { text: "Don't touch that lever. It does nothing. Nothing at all.", lie: true, truth: "That lever makes down point up. Go on.", at: [3, 12, 4, 4] },
      { text: "All right. All right! I'll tell you the truth. Come up here.", lie: false, at: [15, 1, 6, 4] },
    ],
    route: [[5, 15], [11, 10], [11, 7], [12, 6], [3, 6], [18, 6], [19, 2], [16, 3], [19, 1]],
    map: [
      "##############################",
      "#...........^^^......O.......#",
      "#...l...................I....#",
      "#...............a............#",
      "#............................#",
      "###################..#########",
      "#..a..........L..............#",
      "#..........a.............l...#",
      "#............................#",
      "###########..#################",
      "#............................#",
      "#............................#",
      "#.......d...............d....#",
      "#............................#",
      "#............................#",
      "#.S..L.^^^^^^^^^^^^^^^^^^^^^.#",
      "##############################",
    ],
  },
];
