// World 4: Tilted Town (Plan/15-gravity-is-lying.md §5). The camera lies: rooms are shown turned (and
// some a little tilted, gravity hills), so the town looks upright while gravity pulls sideways. The
// houses are built for the camera; the lamps, the drips and the scarf hang the real way.
import type { RoomSource } from "../core/room";

export const WORLD_4: RoomSource[] = [
  {
    id: "4-01",
    name: "Tilted Town",
    gravity: "down",
    view: { up: "right", intro: 75 },
    net: true,
    isaac: [
      { text: "Hold still. Let me straighten this town up for you.", lie: false },
      { text: "There! Much better. Everything's the right way up now.", lie: true, truth: "I turned the camera, not gravity. Down is still where it was. Look at the lamp.", at: 130 },
    ],
    route: [[6, 13], [11, 11], [14, 11], [11, 11], [6, 9], [3, 9], [6, 9], [11, 7], [14, 6]],
    map: [
      "#################",
      "#...............#",
      "#hwr..........d.#",
      "#hIr.....l......#",
      "#Dwr............#",
      "#hhr............#",
      "#hwr..........a.#",
      "#..........O....#",
      "#.........###...#",
      "#hha............#",
      "#hwr.###........#",
      "#Dhr..........a.#",
      "#hwr......###...#",
      "#hhr............#",
      "#....###........#",
      "#TS.....^^^^^^^.#",
      "#################",
    ],
  },
  {
    id: "4-02",
    name: "Lamp Lane",
    gravity: "down",
    levers: ["right"],
    view: { up: "left" },
    arrowLie: "camera",
    isaac: [
      { text: "Lovely street. Nice and level. You could roll a marble down it.", lie: true, truth: "The street is a wall. Down is where the lamps point." },
    ],
    route: [[5, 15], [9, 13], [15, 13], [15, 12], [15, 8], [15, 7], [13, 5], [13, 4], [15, 4]],
    map: [
      "#################",
      "#.........rwhh..#",
      "#.........rhwh..#",
      "#.I.d.....rwhD.O#",
      "#.........rhwa..#",
      "#...............#",
      "#.....l.......###",
      "#...............#",
      "#.............b.#",
      "#..............^#",
      "#.........l....^#",
      "#.........rwhh..#",
      "#.........rhwh.a#",
      "#........arwhD..#",
      "#.........rhwh..#",
      "#.S..L..^^^^....#",
      "#################",
    ],
  },
  {
    id: "4-03",
    name: "Main Street",
    gravity: "down",
    view: { up: "down" },
    arrowLie: "camera",
    flip: true,
    isaac: [
      { text: "Main Street! The finest street in town. Watch out for the potholes.", lie: false },
    ],
    route: [[5, 15], [5, 1], [7, 1], [8, 1], [8, 15], [9, 15], [10, 15], [10, 1], [12, 1], [13, 1]],
    map: [
      "#################",
      "#..^^..a.^^.a.^O#",
      "#hhDh.hhDh.hhDhh#",
      "#whwh.hwhw.whwhw#",
      "#hwhw.whwh.hwhwh#",
      "#rrrr.hwlw.rrrrr#",
      "#.....rrrr......#",
      "#...............#",
      "#...............#",
      "#...............#",
      "#...d...........#",
      "#...............#",
      "#.............I.#",
      "#...............#",
      "#...............#",
      "#.S...^^^a.^^^..#",
      "#################",
    ],
  },
  {
    id: "4-04",
    name: "Gravity Hill",
    gravity: "down",
    view: { up: "up", tilt: 12 },
    arrowLie: "camera",
    isaac: [
      { text: "A hill! Uphill all the way. Mind your legs.", lie: true, truth: "It's just steps. The camera's tilted. Watch the water." },
    ],
    route: [[2, 13], [4, 13], [7, 11], [10, 9], [11, 7], [13, 7], [15, 5], [14, 7]],
    map: [
      "#################",
      "#...............#",
      "#........l......#",
      "#.....d.........#",
      "#...............#",
      "#..............a#",
      "#..l............#",
      "#..........a.O..#",
      "#............####",
      "#.I........T.####",
      "#rr.......##.####",
      "#wh.....T.##.####",
      "#hw....##.##.####",
      "#wa....##.##.####",
      "#hD.##.##.##.####",
      "#.S.##^##^##^####",
      "#################",
    ],
  },
  {
    id: "4-05",
    name: "Rooftops",
    gravity: "down",
    levers: ["left"],
    view: { up: "right", tilt: -8 },
    arrowLie: "camera",
    isaac: [
      { text: "Up on the rooftops! Don't look down. Whichever way that is.", lie: false },
    ],
    route: [[4, 13], [8, 11], [9, 9], [12, 9], [1, 9], [1, 11], [1, 7], [1, 4], [4, 4], [1, 3]],
    map: [
      "#################",
      "#...............#",
      "#O......d.......#",
      "#...............#",
      "#...a.........l.#",
      "#^..............#",
      "#^..............#",
      "#...............#",
      "#...............#",
      "#........a..L...#",
      "#..........###..#",
      "#a........hwhr..#",
      "#......###hhwr..#",
      "#.....hwr.DwhrI.#",
      "#..###Dhr.hhwr..#",
      "#.S...^^^^^^^^^^#",
      "#################",
    ],
  },
  {
    id: "4-06",
    name: "Crooked House",
    gravity: "down",
    zones: [
      { area: [6, 1, 5, 15], dir: "up" },
    ],
    view: { up: "left" },
    arrowLie: "camera",
    isaac: [
      { text: "The crooked house. Its gravity goes up. Up as in... well, you'll see.", lie: false },
    ],
    route: [[5, 15], [8, 8], [8, 1], [10, 1], [15, 8], [14, 15], [11, 15], [8, 8], [9, 1], [11, 3], [12, 4], [12, 6]],
    map: [
      "#################",
      "#............^^^#",
      "#...............#",
      "#.I.............#",
      "#...........a...#",
      "#...............#",
      "#............O..#",
      "#..d.......####.#",
      "#.......a.......#",
      "#..........rhwh.#",
      "#..........rwlh.#",
      "#..........rhwD.#",
      "#..........rwhh.#",
      "#..........rhwh.#",
      "#...............#",
      "#.S...^^^^^...a.#",
      "#################",
    ],
  },
  {
    id: "4-07",
    name: "Upside Downtown",
    gravity: "down",
    view: { up: "down", tilt: 8 },
    arrowLie: "camera",
    flip: true,
    isaac: [
      { text: "Upside-down town. Or is it right-side-up you? Hard to say. Ask your scarf.", lie: false },
    ],
    route: [[4, 15], [4, 1], [8, 1], [11, 1], [8, 9], [13, 9], [14, 9], [14, 15]],
    map: [
      "#################",
      "#^^^....a...^^^^#",
      "#...............#",
      "#...............#",
      "#............l..#",
      "#...............#",
      "#...............#",
      "#...............#",
      "#....#######....#",
      "#hDd....a...hhah#",
      "#hwh........whwh#",
      "#whw........hwhw#",
      "#hwh........whIh#",
      "#rrr........rrrr#",
      "#...............#",
      "#.S..^^^^^^^...O#",
      "#################",
    ],
  },
  {
    id: "4-08",
    name: "Town Square",
    gravity: "down",
    levers: ["left"],
    view: { up: "right" },
    arrowLie: "camera",
    flip: true,
    isaac: [
      { text: "The town square! The heart of Tilted Town. It beats sideways.", lie: false },
    ],
    route: [[4, 15], [4, 1], [8, 1], [11, 1], [14, 15], [1, 12], [1, 8], [1, 6], [8, 6], [15, 6], [15, 2]],
    map: [
      "#################",
      "#.......a...^^^O#",
      "#...............#",
      "#...l..........^#",
      "#^..........d..^#",
      "#^..............#",
      "#.......a.......#",
      "#......###......#",
      "#......###......#",
      "#......###......#",
      "#..I......hhwr..#",
      "#.........hwlr..#",
      "#a........Dhwr..#",
      "#.........hwhr..#",
      "#...............#",
      "#.S..^^^^^^...L.#",
      "#################",
    ],
  },
];
