// The Dev runs: every level, in every layout, must be clearable in 15 s or less once known
// (Plan/06-trapsprint.md §14), and a recording must replay to exactly the same result.
//
// UPDATE_DEV_RUNS=1 pnpm vitest run src/games/trapsprint/levels/dev-runs.test.ts
// re-solves every level and rewrites dev-runs.ts (after a level or physics change).
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { logFromText, logLength, logToText } from "@/engine/replay";
import { MAX_KNOWN_TICKS } from "../core/constants";
import { replay, solve } from "../core/solver";
import { DEV_RUNS, type DevRun } from "./dev-runs";
import { ALL_LEVELS, getLevel } from "./index";

const UPDATE = process.env.UPDATE_DEV_RUNS === "1";

if (UPDATE) {
  it("re-solves every level", { timeout: 1_800_000 }, () => {
    const runs: Record<string, DevRun> = {};
    for (const id of ALL_LEVELS) {
      const level = getLevel(id);
      const first = solve(level);
      if (!first) throw new Error(`${id}: no solution`);
      const run: DevRun = { ticks: first.ticks, log: logToText(first.log) };
      if (level.secondTry) {
        const second = solve(level, { attempt: 1 });
        if (!second) throw new Error(`${id} (after a death): no solution`);
        run.retry = { ticks: second.ticks, log: logToText(second.log) };
      }
      runs[id] = run;
    }
    const lines = Object.entries(runs).map(([id, run]) => {
      const retry = run.retry ? `, retry: { ticks: ${run.retry.ticks}, log: "${run.retry.log}" }` : "";
      return `  "${id}": { ticks: ${run.ticks}, log: "${run.log}"${retry} },`;
    });
    const file = join(process.cwd(), "src/games/trapsprint/levels/dev-runs.ts");
    writeFileSync(
      file,
      `// Generated by levels/dev-runs.test.ts (UPDATE_DEV_RUNS=1): the solver's run through every level.
// They set the Dev medal times, and the tests replay them to prove every level can be cleared.
export interface DevRun {
  ticks: number;
  /** The input recording (engine/replay logToText). */
  log: string;
  /** Levels whose trap moves after your first death: the run through the second layout. */
  retry?: { ticks: number; log: string };
}

export const DEV_RUNS: Record<string, DevRun> = {
${lines.join("\n")}
};
`,
    );
  });
} else {
  describe("dev runs", () => {
    it("exist for every level", () => {
      expect(Object.keys(DEV_RUNS).sort()).toEqual([...ALL_LEVELS].sort());
    });

    it.each(ALL_LEVELS)("%s replays to a win in 15 s or less", (id) => {
      const level = getLevel(id);
      const run = DEV_RUNS[id]!;
      const layouts = [{ attempt: 0, ...run }, ...(run.retry ? [{ attempt: 1, ...run.retry }] : [])];
      for (const { attempt, ticks, log } of layouts) {
        const inputs = logFromText(log);
        expect(logLength(inputs)).toBe(ticks);
        expect(ticks).toBeLessThanOrEqual(MAX_KNOWN_TICKS);
        const end = replay(level, inputs, { attempt });
        expect(end.status).toBe("won");
        expect(end.tick).toBe(ticks);
      }
      expect(level.secondTry).toBe(Boolean(run.retry));
    });
  });
}
