// The story (Plan/07-glitch-run.md §5): twenty stages, each teaching a glitch and mixing in the ones
// before, each ending in a chase by The Debugger. Glitches are placed over chunks (`beat` counts from
// the first chunk; a chunk lasts its beats: see gen/chunks.ts). Every stage is proven clearable, and
// fair, by stages/stages.test.ts.
import type { StageSource } from "./build";

export const STAGES: StageSource[] = [
  {
    id: "01",
    name: "Boot Sequence",
    teaches: "Jump, slide, collect bits. Nothing's broken. Yet.",
    ticks: 30,
    chunks: ["flat", "spike", "block", "gap", "bar", "two-spikes", "step", "spike-pair", "gap-3", "bar-run", "wall", "platform"],
    glitches: [
      { beat: 39, kind: "screenTear", beats: 3 },
    ],
    chase: [{ beat: 3, kind: "low" }, { beat: 6, kind: "high" }, { beat: 9, kind: "low" }],
    chaseBeats: 12,
  },
  {
    id: "02",
    name: "Frame Drop",
    teaches: "Frame Skip: the picture freezes, then jumps. It stutters first, and your shadow keeps going.",
    ticks: 30,
    chunks: ["spike", "gap", "block", "two-spikes", "bar", "wall", "gap-3", "spike-pair", "step", "bar-run", "platform", "stairs", "gap", "two-spikes", "spike"],
    glitches: [
      { beat: 4, kind: "frameSkip", beats: 7 },
      { beat: 15, kind: "frameSkip", beats: 8 },
      { beat: 30, kind: "frameSkip", beats: 7 },
    ],
    chase: [{ beat: 3, kind: "high" }, { beat: 6, kind: "low" }, { beat: 8, kind: "high" }, { beat: 10, kind: "low" }],
    chaseBeats: 12,
  },
  {
    id: "03",
    name: "Swap Meet",
    teaches: "Input Swap: jump and slide trade places. Watch the icons, and your colours.",
    ticks: 30,
    chunks: ["spike", "bar", "spike", "bar", "two-spikes", "gap-3", "wall", "bar-run", "block", "bar", "platform", "spike-pair", "bar", "spike", "gap"],
    glitches: [
      { beat: 4, kind: "inputSwap", beats: 7 },
      { beat: 15, kind: "inputSwap", beats: 7 },
      { beat: 27, kind: "inputSwap", beats: 6 },
    ],
    chase: [{ beat: 3, kind: "low" }, { beat: 5, kind: "high" }, { beat: 7, kind: "high" }, { beat: 9, kind: "low" }],
    chaseBeats: 12,
  },
  {
    id: "04",
    name: "Tear Down",
    teaches: "Screen Tear: the bottom half slides away. Your shadow shows the real floor.",
    ticks: 29,
    chunks: ["gap", "spike-pair", "gap-3", "two-spikes", "gap", "bar-run", "wall", "islands", "spike", "stairs", "patch-hop", "gap-4", "gap-3", "spike", "bar"],
    glitches: [
      { beat: 4, kind: "screenTear", beats: 7 },
      { beat: 16, kind: "screenTear", beats: 6 },
      { beat: 29, kind: "screenTear", beats: 4 },
      { beat: 33, kind: "frameSkip", beats: 4 },
    ],
    chase: [{ beat: 3, kind: "low" }, { beat: 5, kind: "high" }, { beat: 7, kind: "low" }, { beat: 9, kind: "low" }],
    chaseBeats: 12,
  },
  {
    id: "05",
    name: "Missing Assets",
    teaches: "Missing Texture: everything's a magenta checkerboard. Read the shapes.",
    ticks: 29,
    chunks: ["spike", "bar", "spike-bar", "wall", "gap-3", "platform", "two-spikes", "bar-spike", "pillars", "spike", "bar", "high-road", "tunnel", "gap"],
    glitches: [
      { beat: 4, kind: "missingTexture", beats: 7 },
      { beat: 17, kind: "missingTexture", beats: 7 },
      { beat: 24, kind: "inputSwap", beats: 4 },
      { beat: 28, kind: "missingTexture", beats: 8 },
    ],
    chase: [{ beat: 2, kind: "high" }, { beat: 4, kind: "low" }, { beat: 6, kind: "high" }, { beat: 8, kind: "low" }, { beat: 10, kind: "high" }],
    chaseBeats: 12,
  },
  {
    id: "06",
    name: "Negative Space",
    teaches: "Invert: the colours flip, and hidden platforms full of bits show up. They're always there.",
    ticks: 28,
    chunks: ["spike", "gap-3", "hidden-bridge", "bar-run", "wall", "hidden-stairs", "spike-pair", "gap", "hidden-bridge", "triple", "bar", "hidden-stairs"],
    glitches: [
      { beat: 4, kind: "invert", beats: 4 },
      { beat: 13, kind: "invert", beats: 4 },
      { beat: 17, kind: "screenTear", beats: 4 },
      { beat: 21, kind: "invert", beats: 4 },
      { beat: 31, kind: "invert", beats: 4 },
    ],
    chase: [{ beat: 3, kind: "low" }, { beat: 5, kind: "high" }, { beat: 7, kind: "full" }, { beat: 9, kind: "low" }],
    chaseBeats: 12,
  },
  {
    id: "07",
    name: "Lag Spike",
    teaches: "Audio Desync: the picture lags behind the sound. Jump on the sound. Your shadow is on time too.",
    ticks: 28,
    chunks: ["spike", "bar", "two-spikes", "gap-3", "bar", "wall", "spike-bar", "triple", "block", "bar-run", "gap", "spike-pair", "up-and-over", "tunnel"],
    glitches: [
      { beat: 4, kind: "audioDesync", beats: 7 },
      { beat: 16, kind: "audioDesync", beats: 9 },
      { beat: 25, kind: "missingTexture", beats: 4 },
      { beat: 29, kind: "audioDesync", beats: 8 },
    ],
    chase: [{ beat: 2, kind: "low" }, { beat: 4, kind: "high" }, { beat: 6, kind: "low" }, { beat: 8, kind: "full" }, { beat: 10, kind: "high" }],
    chaseBeats: 12,
  },
  {
    id: "08",
    name: "Déjà Vu",
    teaches: "Déjà Vu: the last stretch comes round again, with one change. Spot it.",
    ticks: 28,
    chunks: ["spike", "gap", "triple", "triple*", "bar", "wall", "spike-bar", "spike-bar*", "two-spikes", "bar", "gap-wall", "gap-wall*", "bar-spike", "bar-spike*"],
    glitches: [
      { beat: 8, kind: "dejaVu", beats: 4 },
      { beat: 19, kind: "dejaVu", beats: 3 },
      { beat: 22, kind: "audioDesync", beats: 5 },
      { beat: 30, kind: "dejaVu", beats: 3 },
      { beat: 36, kind: "dejaVu", beats: 3 },
    ],
    chase: [{ beat: 2, kind: "high" }, { beat: 4, kind: "low" }, { beat: 6, kind: "high" }, { beat: 8, kind: "low" }, { beat: 10, kind: "full" }],
    chaseBeats: 12,
  },
  {
    id: "09",
    name: "Low Res",
    teaches: "Low Res: the screen goes chunky. Read the shapes; the cues still sound.",
    ticks: 27,
    chunks: ["spike", "bar", "gap-3", "two-spikes", "bar", "pillars", "spike-bar", "gap-4", "wall", "spike", "triple", "bar-run", "platform"],
    glitches: [
      { beat: 4, kind: "lowRes", beats: 7 },
      { beat: 15, kind: "lowRes", beats: 5 },
      { beat: 20, kind: "frameSkip", beats: 4 },
      { beat: 24, kind: "lowRes", beats: 7 },
    ],
    chase: [{ beat: 2, kind: "low" }, { beat: 4, kind: "low" }, { beat: 6, kind: "high" }, { beat: 8, kind: "high" }, { beat: 10, kind: "full" }],
    chaseBeats: 12,
  },
  {
    id: "10",
    name: "Double Trouble",
    teaches: "Ghost Double: there are two of you. The real one has the shadow, and moves first.",
    ticks: 27,
    chunks: ["spike", "gap", "two-spikes", "bar", "gap-3", "wall-bar", "triple", "spike-gap-bar", "gap", "spike-pair", "zigzag", "bar"],
    glitches: [
      { beat: 4, kind: "ghostDouble", beats: 7 },
      { beat: 14, kind: "ghostDouble", beats: 8 },
      { beat: 22, kind: "screenTear", beats: 4 },
      { beat: 26, kind: "ghostDouble", beats: 4 },
    ],
    chase: [{ beat: 2, kind: "high" }, { beat: 4, kind: "low" }, { beat: 5, kind: "high" }, { beat: 7, kind: "low" }, { beat: 9, kind: "full" }],
    chaseBeats: 12,
  },
  {
    id: "11",
    name: "Mixed Memory I",
    teaches: "Two glitches at once. Each one keeps its own tell.",
    ticks: 26,
    corruption: 20,
    drift: 0.1,
    chunks: ["spike", "bar", "spike-bar", "gap-4", "pillars", "gap", "spike", "bar-spike", "islands", "wall-bar", "gap", "spike", "triple", "spike-gap-bar", "tunnel", "gap", "spike"],
    glitches: [
      { beat: 4, kind: "screenTear", beats: 9 },
      { beat: 6, kind: "inputSwap", beats: 7 },
      { beat: 17, kind: "missingTexture", beats: 10 },
      { beat: 19, kind: "frameSkip", beats: 8 },
      { beat: 31, kind: "lowRes", beats: 12 },
      { beat: 33, kind: "audioDesync", beats: 10 },
    ],
    chase: [{ beat: 2, kind: "low" }, { beat: 3, kind: "high" }, { beat: 5, kind: "low" }, { beat: 7, kind: "full" }, { beat: 9, kind: "high" }, { beat: 10, kind: "low" }],
    chaseBeats: 12,
  },
  {
    id: "12",
    name: "Mixed Memory II",
    teaches: "Two glitches at once. Each one keeps its own tell.",
    ticks: 26,
    corruption: 25,
    drift: 0.1,
    chunks: ["spike", "bar", "bar-spike", "islands", "wall-bar", "gap", "spike", "triple", "spike-gap-bar", "tunnel", "gap", "spike", "high-road", "gap-5", "zigzag", "gap", "spike"],
    glitches: [
      { beat: 4, kind: "inputSwap", beats: 10 },
      { beat: 6, kind: "missingTexture", beats: 8 },
      { beat: 18, kind: "ghostDouble", beats: 12 },
      { beat: 20, kind: "screenTear", beats: 10 },
      { beat: 34, kind: "frameSkip", beats: 11 },
      { beat: 36, kind: "lowRes", beats: 9 },
    ],
    chase: [{ beat: 2, kind: "low" }, { beat: 3, kind: "high" }, { beat: 5, kind: "low" }, { beat: 7, kind: "full" }, { beat: 9, kind: "high" }, { beat: 10, kind: "low" }],
    chaseBeats: 12,
  },
  {
    id: "13",
    name: "Mixed Memory III",
    teaches: "Two glitches at once. Each one keeps its own tell.",
    ticks: 25,
    corruption: 30,
    drift: 0.1,
    chunks: ["spike", "bar", "triple", "spike-gap-bar", "tunnel", "gap", "spike", "high-road", "gap-5", "zigzag", "gap", "spike", "up-and-over", "ceiling-spikes", "bar-pit", "gap", "spike"],
    glitches: [
      { beat: 4, kind: "audioDesync", beats: 12 },
      { beat: 6, kind: "inputSwap", beats: 10 },
      { beat: 20, kind: "invert", beats: 11 },
      { beat: 22, kind: "lowRes", beats: 9 },
      { beat: 35, kind: "missingTexture", beats: 11 },
      { beat: 37, kind: "ghostDouble", beats: 9 },
    ],
    chase: [{ beat: 2, kind: "low" }, { beat: 3, kind: "high" }, { beat: 5, kind: "low" }, { beat: 7, kind: "full" }, { beat: 9, kind: "high" }, { beat: 10, kind: "low" }],
    chaseBeats: 12,
  },
  {
    id: "14",
    name: "Mixed Memory IV",
    teaches: "Two glitches at once. Each one keeps its own tell.",
    ticks: 25,
    corruption: 35,
    drift: 0.1,
    chunks: ["spike", "bar", "high-road", "gap-5", "zigzag", "gap", "spike", "up-and-over", "ceiling-spikes", "bar-pit", "gap", "spike", "spike-bar", "gap-4", "pillars", "gap", "spike"],
    glitches: [
      { beat: 4, kind: "frameSkip", beats: 11 },
      { beat: 6, kind: "screenTear", beats: 9 },
      { beat: 19, kind: "ghostDouble", beats: 11 },
      { beat: 21, kind: "inputSwap", beats: 9 },
      { beat: 34, kind: "audioDesync", beats: 9 },
      { beat: 36, kind: "missingTexture", beats: 7 },
    ],
    chase: [{ beat: 2, kind: "low" }, { beat: 3, kind: "high" }, { beat: 5, kind: "low" }, { beat: 7, kind: "full" }, { beat: 9, kind: "high" }, { beat: 10, kind: "low" }],
    chaseBeats: 12,
  },
  {
    id: "15",
    name: "Mixed Memory V",
    teaches: "Two glitches at once. Each one keeps its own tell.",
    ticks: 25,
    corruption: 40,
    drift: 0.1,
    chunks: ["spike", "bar", "up-and-over", "ceiling-spikes", "bar-pit", "gap", "spike", "spike-bar", "gap-4", "pillars", "gap", "spike", "bar-spike", "islands", "wall-bar", "gap", "spike"],
    glitches: [
      { beat: 4, kind: "lowRes", beats: 11 },
      { beat: 6, kind: "inputSwap", beats: 9 },
      { beat: 19, kind: "screenTear", beats: 9 },
      { beat: 21, kind: "audioDesync", beats: 7 },
      { beat: 32, kind: "frameSkip", beats: 10 },
      { beat: 34, kind: "ghostDouble", beats: 8 },
    ],
    chase: [{ beat: 2, kind: "low" }, { beat: 3, kind: "high" }, { beat: 5, kind: "low" }, { beat: 7, kind: "full" }, { beat: 9, kind: "high" }, { beat: 10, kind: "low" }],
    chaseBeats: 12,
  },
  {
    id: "16",
    name: "Not Responding",
    teaches: "Not Responding: the screen freezes; the game doesn't. Run on the sound and the beat bar.",
    ticks: 25,
    corruption: 30,
    chunks: ["spike", "bar", "gap", "two-spikes", "bar", "wall", "spike-pair", "gap-3", "spike", "bar", "block", "spike-bar", "gap", "triple"],
    glitches: [
      { beat: 6, kind: "notResponding", beats: 5 },
      { beat: 15, kind: "notResponding", beats: 4 },
      { beat: 19, kind: "inputSwap", beats: 4 },
      { beat: 23, kind: "notResponding", beats: 5 },
    ],
    chase: [{ beat: 2, kind: "low" }, { beat: 4, kind: "high" }, { beat: 6, kind: "low" }, { beat: 8, kind: "high" }, { beat: 10, kind: "full" }],
    chaseBeats: 12,
  },
  {
    id: "17",
    name: "Upside Down",
    teaches: "Upside Down: the screen flips over. Your controls don't: jump is still jump.",
    ticks: 24,
    corruption: 35,
    chunks: ["spike", "bar", "two-spikes", "gap-3", "bar-run", "pillars", "spike-bar", "islands", "gap", "wall", "triple", "tunnel"],
    glitches: [
      { beat: 4, kind: "upsideDown", beats: 8 },
      { beat: 16, kind: "upsideDown", beats: 7 },
      { beat: 23, kind: "missingTexture", beats: 4 },
      { beat: 27, kind: "upsideDown", beats: 8 },
    ],
    chase: [{ beat: 2, kind: "high" }, { beat: 4, kind: "low" }, { beat: 6, kind: "high" }, { beat: 8, kind: "full" }, { beat: 10, kind: "low" }],
    chaseBeats: 12,
  },
  {
    id: "18",
    name: "Heap Overflow I",
    teaches: "Everything, all at once, at high corruption. Every tell still holds.",
    ticks: 24,
    corruption: 70,
    drift: 0.2,
    chunks: ["spike", "bar", "spike-bar", "gap-4", "spike", "patch-hop", "pillars", "bar-spike", "spike", "patch-hop", "islands", "wall-bar", "spike", "patch-hop", "triple", "spike-gap-bar", "spike", "patch-hop"],
    glitches: [
      { beat: 4, kind: "screenTear", beats: 5 },
      { beat: 6, kind: "inputSwap", beats: 3 },
      { beat: 14, kind: "lowRes", beats: 7 },
      { beat: 16, kind: "missingTexture", beats: 5 },
      { beat: 26, kind: "audioDesync", beats: 7 },
      { beat: 28, kind: "ghostDouble", beats: 5 },
      { beat: 38, kind: "frameSkip", beats: 8 },
      { beat: 40, kind: "notResponding", beats: 6 },
    ],
    chase: [{ beat: 2, kind: "low" }, { beat: 3, kind: "high" }, { beat: 5, kind: "full" }, { beat: 6, kind: "low" }, { beat: 8, kind: "high" }, { beat: 9, kind: "full" }, { beat: 11, kind: "low" }],
    chaseBeats: 14,
  },
  {
    id: "19",
    name: "Heap Overflow II",
    teaches: "Everything, all at once, at high corruption. Every tell still holds.",
    ticks: 23,
    corruption: 80,
    drift: 0.2,
    chunks: ["spike", "bar", "spike-bar", "gap-4", "spike", "patch-hop", "pillars", "bar-spike", "spike", "patch-hop", "islands", "wall-bar", "spike", "patch-hop", "triple", "spike-gap-bar", "spike", "patch-hop"],
    glitches: [
      { beat: 4, kind: "upsideDown", beats: 5 },
      { beat: 6, kind: "audioDesync", beats: 3 },
      { beat: 14, kind: "inputSwap", beats: 7 },
      { beat: 16, kind: "screenTear", beats: 5 },
      { beat: 26, kind: "notResponding", beats: 7 },
      { beat: 28, kind: "lowRes", beats: 5 },
      { beat: 38, kind: "ghostDouble", beats: 8 },
      { beat: 40, kind: "missingTexture", beats: 6 },
    ],
    chase: [{ beat: 2, kind: "low" }, { beat: 3, kind: "high" }, { beat: 5, kind: "full" }, { beat: 6, kind: "low" }, { beat: 8, kind: "high" }, { beat: 9, kind: "full" }, { beat: 11, kind: "low" }],
    chaseBeats: 14,
  },
  {
    id: "20",
    name: "Root",
    teaches: "The Debugger, all the way to the Root folder. You start fully charged: you'll need it.",
    ticks: 22,
    corruption: 60,
    charges: 3,
    chunks: ["bits-high", "spike", "bar", "gap-3", "spike-bar", "platform", "bits-high", "bar-spike", "triple", "two-spikes", "gap", "bits-high", "spike"],
    glitches: [
      { beat: 7, kind: "screenTear", beats: 5 },
      { beat: 18, kind: "inputSwap", beats: 7 },
      { beat: 25, kind: "notResponding", beats: 5 },
      { beat: 41, kind: "lowRes", beats: 4 },
      { beat: 47, kind: "missingTexture", beats: 6 },
    ],
    chase: [{ beat: 2, kind: "low" }, { beat: 3, kind: "full" }, { beat: 5, kind: "high" }, { beat: 6, kind: "low" }, { beat: 8, kind: "full" }, { beat: 10, kind: "high" }, { beat: 11, kind: "low" }, { beat: 13, kind: "full" }, { beat: 15, kind: "low" }, { beat: 17, kind: "high" }],
    chaseBeats: 20,
    finale: { deleting: ["gap", "spike-pair", "gap-3"], reformat: ["spike", "bar", "two-spikes", "gap", "spike-bar"] },
  },
];
