// 5. The Bakery (Plan/11-panic-stack.md §5): cakes, loaves and ice; squishing, melting, and the ice age.
import { belt, level, pool } from "./kit";

export const BAKERY = [
  level({
    id: "5-1",
    name: "Layer Cake",
    location: "bakery",
    time: 110,
    goal: 2.2,
    platform: 4,
    items: belt("loaf brick cake loaf brick crate cake loaf brick loaf crate"),
    more: pool("loaf brick crate"),
    belt: 21,
    events: [],
    hint: "Cakes make a lovely solid base.",
  }),
  level({
    id: "5-2",
    name: "On Ice",
    location: "bakery",
    time: 110,
    goal: 2.4,
    platform: 4,
    items: belt("loaf brick ice crate loaf brick ice loaf crate brick loaf crate"),
    more: pool("loaf brick crate"),
    belt: 21,
    events: [],
    hint: "Keep the cream cool. Ice cubes are nice and square.",
  }),
  level({
    id: "5-3",
    name: "Cold Snap",
    location: "bakery",
    time: 110,
    goal: 2.6,
    platform: 4,
    items: belt("loaf brick crate cake loaf brick crate ice loaf brick crate loaf brick"),
    more: pool("loaf brick crate"),
    belt: 19,
    events: [
      { kind: "iceAge", at: 22 },
      { kind: "iceAge", at: 58 },
    ],
    hint: "The freezer door's stuck open.",
  }),
  level({
    id: "5-4",
    name: "Bake Sale",
    location: "bakery",
    time: 100,
    goal: 2.8,
    platform: 4,
    items: belt("loaf brick cake crate ice loaf brick jelly crate loaf cake brick crate loaf"),
    more: pool("loaf brick crate cake"),
    belt: 17,
    events: [
      { kind: "conveyorRush", at: 20 },
      { kind: "iceAge", at: 50 },
    ],
    hint: "Everything must go. Fast.",
  }),
  level({
    id: "5-5",
    name: "Rising Dough",
    location: "bakery",
    time: 110,
    goal: 3,
    platform: 4,
    items: belt("loaf brick crate balloon loaf cake brick crate xray ice loaf brick crate loaf brick"),
    more: pool("loaf brick crate cake"),
    belt: 17,
    events: [{ kind: "iceAge", at: 18 }],
    random: { kinds: ["iceAge", "earthquake", "fakePanic", "conveyorRush"], every: [15, 22] },
    hint: "It's warm in here. Things grow, and things melt.",
  }),
  level({
    id: "5-6",
    name: "Wedding Cake",
    location: "bakery",
    time: 120,
    goal: 3.4,
    platform: 4,
    items: belt("crate loaf brick cake crate ice loaf brick jelly crate cake loaf brick crate balloon loaf brick"),
    more: pool("loaf brick crate cake"),
    belt: 16,
    events: [],
    random: { kinds: ["iceAge", "earthquake", "fakePanic", "conveyorRush", "wind"], every: [14, 20] },
    hint: "Five tiers, and it has to stand through the speeches.",
  }),
];
