// 1. The Kitchen (Plan/11-panic-stack.md §5): plates, loaves, bricks; the first liar (the rolling box), jelly,
// and the first earthquakes.
import { belt, level, pool } from "./kit";

export const KITCHEN = [
  level({
    id: "1-1",
    name: "Plate Stack",
    location: "kitchen",
    time: 90,
    goal: 1.6,
    platform: 4,
    items: belt("plate loaf plate brick loaf plate brick loaf plate brick"),
    more: pool("plate loaf brick"),
    belt: 21,
    events: [],
    hint: "Drag things off the belt and stack them up to the line. Then hold still for three seconds.",
  }),
  level({
    id: "1-2",
    name: "Square One",
    location: "kitchen",
    time: 100,
    goal: 2,
    platform: 4,
    items: belt("brick loaf box plate brick loaf box plate brick loaf plate"),
    more: pool("plate loaf brick box"),
    belt: 21,
    events: [],
    hint: "Tap anything on the belt to hear what it's really made of. Q and E (or the turn buttons) turn what you're holding.",
  }),
  level({
    id: "1-3",
    name: "Tremor",
    location: "kitchen",
    time: 100,
    goal: 2.2,
    platform: 4,
    items: belt("brick plate loaf brick box plate brick loaf plate brick loaf"),
    more: pool("plate loaf brick box"),
    belt: 20,
    events: [
      { kind: "earthquake", at: 22, strength: 0.7 },
      { kind: "earthquake", at: 55, strength: 0.8 },
    ],
    hint: "When the seismograph twitches, stop and let it pass.",
  }),
  level({
    id: "1-4",
    name: "Set Jelly",
    location: "kitchen",
    time: 100,
    goal: 2.2,
    platform: 4,
    items: belt("brick plate jelly loaf brick plate jelly brick loaf plate brick"),
    more: pool("plate loaf brick jelly"),
    belt: 20,
    events: [],
    hint: "That jelly looks nice and firm.",
  }),
  level({
    id: "1-5",
    name: "Lunch Rush",
    location: "kitchen",
    time: 90,
    goal: 2.6,
    platform: 4,
    items: belt("brick box plate jelly loaf brick box plate brick loaf jelly plate brick"),
    more: pool("plate loaf brick box jelly"),
    belt: 18,
    events: [
      { kind: "earthquake", at: 18, strength: 0.8 },
      { kind: "earthquake", at: 50, strength: 0.9 },
    ],
    hint: "Less time, a higher line. The kitchen's busy.",
  }),
  level({
    id: "1-6",
    name: "Dinner Party",
    location: "kitchen",
    time: 100,
    goal: 3,
    platform: 4,
    items: belt("brick plate box loaf brick jelly plate brick box loaf plate brick jelly loaf brick"),
    more: pool("plate loaf brick box jelly"),
    belt: 18,
    events: [
      { kind: "earthquake", at: 15, strength: 0.8 },
      { kind: "earthquake", at: 45, strength: 1 },
      { kind: "earthquake", at: 75, strength: 0.9 },
    ],
    hint: "Everyone's coming. Stack it high.",
  }),
];
