// 4. The Museum (Plan/11-panic-stack.md §5): statues and vases; fragile things, careful placement, lights
// out, pigeons and a shrinking platform.
import { belt, level, pool } from "./kit";

export const MUSEUM = [
  level({
    id: "4-1",
    name: "Handle With Care",
    location: "museum",
    time: 120,
    goal: 2.4,
    platform: 4,
    items: belt("crate brick vase statue brick crate vase brick crate statue brick"),
    more: pool("crate brick statue"),
    belt: 22,
    events: [],
    hint: "Priceless. Probably.",
  }),
  level({
    id: "4-2",
    name: "Statuesque",
    location: "museum",
    time: 110,
    goal: 2.9,
    platform: 4,
    items: belt("statue brick vase crate statue brick vase crate brick vase statue crate brick"),
    more: pool("crate brick statue"),
    belt: 20,
    events: [{ kind: "earthquake", at: 40, strength: 0.7 }],
    hint: "Statues are heavy and tall. Lying down, they're just heavy.",
  }),
  level({
    id: "4-3",
    name: "Power Cut",
    location: "museum",
    time: 110,
    goal: 3,
    platform: 4,
    items: belt("crate brick statue box brick crate vase brick crate statue box brick crate"),
    more: pool("crate brick statue box"),
    belt: 19,
    events: [
      { kind: "lightsOut", at: 20 },
      { kind: "lightsOut", at: 55 },
    ],
    hint: "In the dark you only see shadows. Shadows don't lie.",
  }),
  level({
    id: "4-4",
    name: "Pigeons",
    location: "museum",
    time: 110,
    goal: 3.2,
    platform: 4,
    items: belt("crate brick statue vase crate brick vase crate brick statue crate brick crate brick"),
    more: pool("crate brick statue"),
    belt: 19,
    events: [
      { kind: "bird", at: 25 },
      { kind: "bird", at: 60 },
    ],
    hint: "Somebody's been feeding the pigeons on the roof.",
  }),
  level({
    id: "4-5",
    name: "Renovation",
    location: "museum",
    time: 110,
    goal: 3.2,
    platform: 5,
    items: belt("crate brick statue crate brick vase box brick crate statue brick crate brick"),
    more: pool("crate brick statue box"),
    belt: 18,
    events: [
      { kind: "platformShrink", at: 28 },
      { kind: "platformShrink", at: 62 },
    ],
    hint: "The builders are in. Watch the edges.",
  }),
  level({
    id: "4-6",
    name: "Grand Opening",
    location: "museum",
    time: 120,
    goal: 3.6,
    platform: 4.5,
    items: belt("crate statue brick vase crate brick box vase statue xray crate brick vase crate statue brick crate brick"),
    more: pool("crate brick statue box vase"),
    belt: 16,
    events: [{ kind: "lightsOut", at: 15 }],
    random: { kinds: ["bird", "lightsOut", "earthquake", "fakePanic", "platformShrink"], every: [15, 22] },
    hint: "Doors open at noon. Nothing can break.",
  }),
];
