// 6. The Space Station (Plan/11-panic-stack.md §5): cargo pods in low gravity; low gravity events, magnets,
// tilt, the re-skin, and everything at once.
import { belt, level, pool } from "./kit";

export const SPACE = [
  level({
    id: "6-1",
    name: "Zero-G Lunch",
    location: "space",
    time: 110,
    goal: 2.6,
    platform: 4,
    gravity: 6,
    items: belt("cargo brick crate cargo brick crate cargo brick crate cargo brick"),
    more: pool("cargo brick crate"),
    belt: 20,
    events: [
      { kind: "lowGravity", at: 22 },
      { kind: "lowGravity", at: 58 },
    ],
    hint: "Gravity's lighter up here. And sometimes lighter still.",
  }),
  level({
    id: "6-2",
    name: "Attraction",
    location: "space",
    time: 110,
    goal: 2.6,
    platform: 4,
    gravity: 6,
    items: belt("crate brick magnet crate cargo brick crate magnet brick crate cargo brick"),
    more: pool("crate brick cargo"),
    belt: 20,
    events: [],
    hint: "Somebody's left their paperweight lying around.",
  }),
  level({
    id: "6-3",
    name: "Listing",
    location: "space",
    time: 110,
    goal: 2.8,
    platform: 4,
    gravity: 6,
    items: belt("cargo brick crate box cargo brick crate magnet brick crate cargo brick crate"),
    more: pool("cargo brick crate"),
    belt: 19,
    events: [
      { kind: "tilt", at: 20 },
      { kind: "tilt", at: 55 },
    ],
    hint: "The station's thrusters are acting up.",
  }),
  level({
    id: "6-4",
    name: "Texture Pack",
    location: "space",
    time: 110,
    goal: 2.8,
    platform: 4,
    gravity: 6,
    items: belt("cargo safe brick crate feather cargo brick xray crate box cargo brick crate safe brick crate"),
    more: pool("cargo brick crate feather"),
    belt: 18,
    events: [{ kind: "reskin", at: 24 }],
    hint: "The textures are still loading. Don't believe your eyes; believe your ears.",
  }),
  level({
    id: "6-5",
    name: "Mission Control",
    location: "space",
    time: 120,
    goal: 3.2,
    platform: 4,
    gravity: 6,
    items: belt("cargo brick crate magnet cargo brick feather crate box cargo xray brick crate safe cargo brick crate"),
    more: pool("cargo brick crate feather box"),
    belt: 16,
    events: [{ kind: "reskin", at: 30 }],
    random: { kinds: ["tilt", "lowGravity", "fakePanic", "conveyorRush", "earthquake"], every: [14, 20] },
    hint: "Everything you've learned, in orbit.",
  }),
  level({
    id: "6-6",
    name: "The Final Stack",
    location: "space",
    time: 150,
    goal: 4,
    platform: 4,
    gravity: 6,
    items: belt("cargo crate brick feather cargo box crate brick duck cargo xray crate brick magnet cargo crate brick box cargo crate brick"),
    more: pool("cargo brick crate box duck feather"),
    belt: 15,
    events: [{ kind: "reskin", at: 40 }],
    random: { kinds: ["tilt", "lowGravity", "fakePanic", "earthquake", "wind", "cat", "bird", "conveyorRush"], every: [13, 19] },
    hint: "Four metres, in orbit, with the cat. Good luck.",
  }),
];
