// 3. The Toy Room (Plan/11-panic-stack.md §5): toy blocks, rubber ducks, balloons; the sticky duck, the
// growing balloon, the cat, and the first fake panic.
import { belt, level, pool } from "./kit";

export const TOYROOM = [
  level({
    id: "3-1",
    name: "Rubber Ducky",
    location: "toyroom",
    time: 110,
    goal: 2.4,
    platform: 4,
    items: belt("block brick duck block brick duck block brick block duck brick"),
    more: pool("block brick duck"),
    belt: 21,
    events: [],
    hint: "Ducks bounce. Everybody knows that.",
  }),
  level({
    id: "3-2",
    name: "Party Balloons",
    location: "toyroom",
    time: 110,
    goal: 2.4,
    platform: 4,
    items: belt("block brick balloon block brick duck balloon block brick block brick"),
    more: pool("block brick duck"),
    belt: 21,
    events: [],
    hint: "A balloon or two for the party.",
  }),
  level({
    id: "3-3",
    name: "Here, Kitty",
    location: "toyroom",
    time: 110,
    goal: 2.6,
    platform: 4,
    items: belt("block brick block duck brick block box brick block duck brick block"),
    more: pool("block brick duck box"),
    belt: 20,
    events: [{ kind: "cat", at: 30, dir: 1 }],
    hint: "Something's been batting at the toys.",
  }),
  level({
    id: "3-4",
    name: "Toy Siren",
    location: "toyroom",
    time: 100,
    goal: 2.8,
    platform: 4,
    items: belt("block brick duck block brick box block brick balloon block brick duck block"),
    more: pool("block brick duck box"),
    belt: 19,
    events: [
      { kind: "fakePanic", at: 16 },
      { kind: "wind", at: 40, strength: 0.8 },
      { kind: "fakePanic", at: 64 },
    ],
    hint: "Not every alarm is real. Look at the siren.",
  }),
  level({
    id: "3-5",
    name: "Playtime",
    location: "toyroom",
    time: 110,
    goal: 3,
    platform: 4,
    items: belt("block brick duck block box brick balloon block bowling brick duck block brick box block brick"),
    more: pool("block brick duck box balloon bowling"),
    belt: 17,
    events: [{ kind: "cat", at: 25 }],
    random: { kinds: ["fakePanic", "wind", "earthquake"], every: [16, 22] },
    hint: "The cat, the wind, and a siren that might be lying.",
  }),
  level({
    id: "3-6",
    name: "Toy Box",
    location: "toyroom",
    time: 120,
    goal: 3.4,
    platform: 4,
    items: belt("block brick duck block box brick block balloon duck brick block box brick duck block brick"),
    more: pool("block brick duck box balloon"),
    belt: 16,
    events: [],
    random: { kinds: ["cat", "fakePanic", "wind", "earthquake", "conveyorRush"], every: [14, 20] },
    hint: "Everything out of the toy box at once.",
  }),
];
