// 2. The Warehouse (Plan/11-panic-stack.md §5): crates, anvils, safes; the floating safe, the lead feather,
// wind and the conveyor rush.
import { belt, level, pool } from "./kit";

export const WAREHOUSE = [
  level({
    id: "2-1",
    name: "Heavy Lifting",
    location: "warehouse",
    time: 110,
    goal: 2.2,
    platform: 4,
    items: belt("crate brick safe anvil brick crate brick safe brick crate brick"),
    more: pool("crate brick anvil"),
    belt: 21,
    events: [],
    hint: "Heavy things at the bottom, obviously. That safe must weigh a ton.",
  }),
  level({
    id: "2-2",
    name: "Light as a Feather",
    location: "warehouse",
    time: 110,
    goal: 2.2,
    platform: 4,
    items: belt("crate brick feather crate brick feather crate brick crate brick"),
    more: pool("crate brick"),
    belt: 21,
    events: [],
    hint: "Feathers on top, where they can't hurt anyone.",
  }),
  level({
    id: "2-3",
    name: "Draughty",
    location: "warehouse",
    time: 100,
    goal: 2.6,
    platform: 4,
    items: belt("crate brick anvil crate brick feather crate brick crate safe brick crate"),
    more: pool("crate brick anvil"),
    belt: 19,
    events: [
      { kind: "wind", at: 20, strength: 0.8 },
      { kind: "wind", at: 55, strength: 1 },
    ],
    hint: "Somebody left the loading-bay door open.",
  }),
  level({
    id: "2-4",
    name: "Rush Hour",
    location: "warehouse",
    time: 100,
    goal: 2.8,
    platform: 4,
    items: belt("crate brick crate anvil brick crate feather brick bowling crate brick safe crate brick"),
    more: pool("crate brick anvil bowling"),
    belt: 18,
    events: [
      { kind: "conveyorRush", at: 16 },
      { kind: "conveyorRush", at: 52 },
    ],
    hint: "When the gears whine, the belt doubles its speed.",
  }),
  level({
    id: "2-5",
    name: "Overtime",
    location: "warehouse",
    time: 100,
    goal: 3,
    platform: 4,
    items: belt("crate anvil brick feather crate brick safe crate brick anvil crate brick feather crate"),
    more: pool("crate brick anvil feather"),
    belt: 17,
    events: [
      { kind: "wind", at: 14 },
      { kind: "conveyorRush", at: 38 },
      { kind: "earthquake", at: 62, strength: 0.9 },
    ],
    hint: "Wind, rush, rumble. In that order.",
  }),
  level({
    id: "2-6",
    name: "Stocktake",
    location: "warehouse",
    time: 120,
    goal: 3.4,
    platform: 4,
    items: belt("crate anvil brick crate feather brick safe crate brick anvil crate brick feather crate brick safe"),
    more: pool("crate brick anvil feather safe"),
    belt: 17,
    events: [{ kind: "wind", at: 12, strength: 0.9 }],
    random: { kinds: ["wind", "earthquake", "conveyorRush"], every: [16, 24] },
    hint: "Count everything. Trust nothing.",
  }),
];
