// The solver's runs: every room must be crossable, and a recording must replay to exactly the same
// result (Plan/05-fake-floor.md §14: "All 51 rooms are completable").
//
// UPDATE_DEV_RUNS=1 pnpm vitest run src/games/fake-floor/rooms/dev-runs.test.ts
// re-solves every room and rewrites dev-runs.ts (after a room or physics change).
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { logFromText, logLength, logToText } from "@/engine/replay";
import { MAX_KNOWN_TICKS } from "../core/constants";
import { clockTicks, replay, solve } from "../core/solver";
import { DEV_RUNS, type DevRun } from "./dev-runs";
import { getRoom, ROOM_IDS } from "./index";

const UPDATE = process.env.UPDATE_DEV_RUNS === "1";

if (UPDATE) {
  it("re-solves every room", { timeout: 3_600_000 }, () => {
    const runs: Record<string, DevRun> = {};
    for (const id of ROOM_IDS) {
      const found = solve(getRoom(id));
      if (!found) throw new Error(`${id}: no solution`);
      runs[id] = { time: found.time, ticks: found.ticks, log: logToText(found.log) };
    }
    const lines = Object.entries(runs).map(([id, run]) => `  "${id}": { time: ${run.time}, ticks: ${run.ticks}, log: "${run.log}" },`);
    writeFileSync(
      join(process.cwd(), "src/games/fake-floor/rooms/dev-runs.ts"),
      `// Generated by rooms/dev-runs.test.ts (UPDATE_DEV_RUNS=1): the solver's run through every room.
// They set the par times, and the tests replay them to prove every room can be crossed.
export interface DevRun {
  /** From the first step to the door (what the game's clock measures), in ticks. */
  time: number;
  /** The whole recording, in ticks. */
  ticks: number;
  /** The input recording (engine/replay logToText). */
  log: string;
}

export const DEV_RUNS: Record<string, DevRun> = {
${lines.join("\n")}
};
`,
    );
  });
} else {
  describe("dev runs", () => {
    it("exist for every room", () => {
      expect(Object.keys(DEV_RUNS).sort()).toEqual([...ROOM_IDS].sort());
    });

    it.each(ROOM_IDS)("%s replays to the door in a minute or less", (id) => {
      const run = DEV_RUNS[id]!;
      const inputs = logFromText(run.log);
      expect(logLength(inputs)).toBe(run.ticks);
      expect(clockTicks(inputs)).toBe(run.time);
      expect(run.ticks).toBeLessThanOrEqual(MAX_KNOWN_TICKS);
      const end = replay(getRoom(id), inputs);
      expect(end.status).toBe("won");
      expect(end.tick).toBe(run.ticks);
    });
  });
}
