// Generated by world/feathers.test.ts (UPDATE_FEATHERS=1): a fair detour to each Lost Feather, from a
// spot on the climb's route (on the mountain and on Mirror Mountain).
export interface FeatherRun {
  index: number;
  /** Where on the route it starts: the climb up, or after the summit falls. */
  phase: "up" | "down";
  /** Ticks into that part of the route. */
  at: number;
  /** The detour (engine/replay logToText). */
  log: string;
}

export const FEATHER_RUNS: Record<"normal" | "mirror", FeatherRun[]> = {
  normal: [
    { index: 0, phase: "up", at: 688, log: "AgYGJAIBADACJAYYAgEAIAUVAQEAGwESBSIBAQAuASQFDwEBACoBDQ" },
    { index: 1, phase: "up", at: 2519, log: "ARIFIgEBACkBHgUiAQEAWQ" },
    { index: 2, phase: "up", at: 3289, log: "BRcBAQAaBh0CAQAqAhM" },
    { index: 3, phase: "up", at: 4445, log: "BgECAQAS" },
    { index: 4, phase: "up", at: 7361, log: "AgYGGAIBACACBQ" },
    { index: 5, phase: "up", at: 8905, log: "Bg8CAQAt" },
    { index: 6, phase: "up", at: 10860, log: "ARgFGgEBACABGAYWAgEAHQIGBhwCAQAgBhQCAQAwAg8" },
    { index: 7, phase: "down", at: 667, log: "Bh0CAQAn" },
    { index: 8, phase: "down", at: 1123, log: "AR4FIgEBAC4BAw" },
    { index: 9, phase: "down", at: 3799, log: "AQwFIgEBADMBDQ" },
    { index: 10, phase: "down", at: 5098, log: "BRoBAQAgAR4FIwEBAC0BEgUeAQEAJgYYAgEAIAISBiICAQAvAiQGDQIBAC8CDQ" },
    { index: 11, phase: "down", at: 6626, log: "AR4FIQEBADIBBA" },
  ],
  mirror: [
    { index: 0, phase: "up", at: 693, log: "AQwFIgEBAC4BJAUXAQEAHwYUAgEAGQISBiQCAQAwAiQGDwIBACoCDA" },
    { index: 1, phase: "up", at: 2126, log: "BRcBAQAfAQYFIgEBAC4BGAUeAQEAJgYbAgEAJAIqBhgCAQAgAhIGJAIBACwCGAYkAgEAWw" },
    { index: 2, phase: "up", at: 3307, log: "BhcCAQAaBR0BAQAqARM" },
    { index: 3, phase: "up", at: 4449, log: "BQEBAQAS" },
    { index: 4, phase: "up", at: 7362, log: "AQYFFwEBAB8BBQ" },
    { index: 5, phase: "up", at: 9004, log: "BQoBAQApAgU" },
    { index: 6, phase: "up", at: 10941, log: "AhgGGgIBACACGAUWAQEAHQEGBRwBAQAgBRQBAQAwAQ8" },
    { index: 7, phase: "down", at: 673, log: "BR0BAQAn" },
    { index: 8, phase: "down", at: 1129, log: "Ah4GIgIBAC4CAw" },
    { index: 9, phase: "down", at: 3805, log: "AgwGIgIBADMCDQ" },
    { index: 10, phase: "down", at: 5147, log: "BhkCAQAeAh4GJAIBAC4CEgYeAgEAJgUXAQEAHwESBSMBAQAxAR4FDwEBADEBDQ" },
    { index: 11, phase: "down", at: 6683, log: "AhgGJAIBADQCBg" },
  ],
};
